apiVersion: v1
kind: Service
metadata:
  name: PythonApp
  namespace: pyhonapp
spec:
  type: LoadBalancer
  selector:
    app: PythonApp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000