name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

env:
  workspace-name: myWorkspace # name of the Azure Machine Learning workspace
  resource-group: myResourceGroup # name of the Azure resource group

permissions:
  id-token: write
  contents: read

jobs:
  initialise_vars:
    runs-on: ubuntu-latest
    outputs:
      workspace-name: ${{ env.workspace-name }}
      resource-group: ${{ env.resource-group }}
    steps:
      - name: Initialise Variables
        run: echo "Initialising environment variables"

  train:
    needs: initialise_vars
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job.yml --workspace-name ${{ needs.initialise_vars.outputs.workspace-name }} --resource-group ${{ needs.initialise_vars.outputs.resource-group }}