name: Deploy Model

on:
  pull_request_target:
    types: [labeled, unlabeled]

env:
  workspace-name: myWorkspace # name of the Azure Machine Learning workspace
  resource-group: myResourceGroup # name of the Azure resource group
  job-name: lime_queen_k194g7dtrk # name of the job that contains the model
  model-name: my-model # name of the model
  endpoint-name: my-endpoint # name of the endpoint
  deployment-name: my-deployment # name of the deployment

permissions:
  id-token: write
  contents: read

jobs:
  register-model:
    if: contains(github.event.pull_request.labels.*.name, 'register-model')
    name: Register Model
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Trigger Azure ML job
        run: az ml model create --name ${{ env.model-name }} --version 1 --path runs:/${{ env.job-name }}/model/ --type mlflow_model
  create-endpoint:
    name: Create Endpoint
    if: contains(github.event.pull_request.labels.*.name, 'create-endpoint')
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Trigger Azure ML job
        run: az ml online-endpoint create --name ${{ env.endpoint-name }} -f src/create-endpoint.yml
  deploy-model:
    name: Deploy Model
    if: contains(github.event.pull_request.labels.*.name, 'deploy-model')
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Trigger Azure ML job
        run:  az ml online-deployment create --name ${{ env.deployment-name }} --endpoint ${{ env.endpoint-name }} -f src/mlflow-deployment.yml --all-traffic

        