on:
    workflow_dispatch:
  
permissions:
    id-token: write
    contents: read
  
env:
    resource-group: myResourceGroup # name of the Azure resource group
    ml-workspace: myWorkspace # name of the Azure Machine Learning workspace
    ml-endpoint: 'https://mlflow-endpoint-1.australiaeast.inference.ml.azure.com/score' # name of the Azure Machine Learning endpoint
  
jobs:
    bicep-whatif:
      name: 'Bicep What-If'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Retrieve API key
          run: |
            ENDPOINT_KEY=$(az ml online-endpoint get-credentials -n ${{ env.ml-endpoint }} -g ${{ env.resource-group }} -w ${{ env.ml-workspace }} -o tsv --query primaryKey)
            echo ::add-mask::$ENDPOINT_KEY
            echo ENDPOINT_KEY=$ENDPOINT_KEY >> $GITHUB_ENV
  
        # Run what-if deployment
        - name: What-If
          uses: azure/arm-deploy@v1
          with:
            scope: resourcegroup
            failOnStdErr: false
            resourceGroupName: ${{ env.resource-group }}
            template: src\infra\main.bicep
            parameters: 'AZURE_ML_ENDPOINT_URL=${{ env.ml-endpoint }} API_KEY=${{ env.ENDPOINT_KEY }}'
            additionalArguments: --what-if
  
    bicep-deploy:
      name: 'Bicep Deploy'
      runs-on: ubuntu-latest
      environment: prod
      needs: [bicep-whatif]
      
      steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
  
        # Authenticate to Az CLI using OIDC
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        # Deploy
        - name: Deploy
          uses: azure/arm-deploy@v1
          with:
            scope: resourcegroup
            failOnStdErr: false
            resourceGroupName: ${{ env.resource-group }}
            template: src\infra\main.bicep
            parameters: 'AZURE_ML_ENDPOINT_URL=${{ env.ml-endpoint }} API_KEY=${{ env.ENDPOINT_KEY }}'
  