on:
    workflow_dispatch:
  
permissions:
    id-token: write
    contents: read
  
env:
    resource-group: myResourceGroup # name of the Azure resource group
  
jobs:
    bicep-whatif:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
        # Run what-if deployment
        - name: "What-If"
          uses: Azure/cli@v1
          with:
            inlineScript: |
                az deployment group what-if
                --name whatif-${{ github.run_id }} \
                --template-file src\infra\main.bicepp \
                --resource-group ${{ env.resource-group }} > whatif
  
        - name: Create String Output
          id: whatif-string
          run: |
            WHATIF=$(cat whatif)
            
            delimiter="$(openssl rand -hex 8)"
            echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
            echo "## Whatif Output" >> $GITHUB_OUTPUT
            echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
            echo "$WHATIF" >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
            echo "</details>" >> $GITHUB_OUTPUT
            echo "${delimiter}" >> $GITHUB_OUTPUT
  
        # Publish Terraform Plan as task summary
        - name: Publish Whatif to Task Summary
          env:
            SUMMARY: ${{ steps.whatif-string.outputs.summary }}
          run: |
            echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        
        # If this is a PR post the changes
        - name: Push Whatif Output to PR
          if: github.ref != 'refs/heads/main'
          uses: actions/github-script@v6
          env:
            SUMMARY: "${{ steps.whatif-string.outputs.summary }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const body = `${process.env.SUMMARY}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })
  
    bicep-deploy:
      name: 'Bicep Deploy'
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment: prod
      needs: [bicep-whatif]
      
      steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
  
        # Authenticate to Az CLI using OIDC
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
        # Deploy
        - name: "Bicep Deployment"
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group create \
              --name deploy-${{ github.run_id }} \
              --template-file src\infra\main.bicepp \
              --resource-group ${{ env.resource-group }}
  